### ISSUE TITLE
How to upgrade to Vite 3? Vite errors due to this plugin

### ISSUE THREAD

**Issue by dfalling** [jihchi/vite-plugin-rescript#11]
Hi, I'm trying to upgrade Vite to `3.0.1` and this plugin to `3.1.1`. When I try to start the dev server, Vite complains about a `require()` in the plugin:

```
failed to load config from vite.config.js
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@jihchi/vite-plugin-rescript/node_modules/execa/index.js
from node_modules/@jihchi/vite-plugin-rescript/dist/index.cjs not supported.
Instead change the require of index.js in node_modules/@jihchi/vite-plugin-rescript/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
at Object.require.extensions.<computed> [as .js] (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:62001:13)
...
error Command failed with exit code 1.
```

Is there something else I need to do to upgrade to Vite 3?

Thanks!

**Comment by daniel-nagy** [comment]
A bit unfortunate but you can work around this with a dynamic import in **vite.config.ts**.

```typescript
export default async () => {
  const reScript = (await import("@jihchi/vite-plugin-rescript")).default;

  return defineConfig({
    ...,
    plugins: [reScript(), ...]
  });
};
```

**Comment by jihchi** [comment]
I've published a new version: `4.1.0`, hope it can fix/mitigate the problem.

Please use following code if you want to keep using `require` syntax:

```js
const { default: createReScriptPlugin } = require('@jihchi/vite-plugin-rescript');
```

**Comment by daniel-nagy** [comment]
Thanks, `4.1.0` seems to be working for me.

**Comment by dfalling** [comment]
That fixed it for me too!

Just a note for others: something changed with Vite, and I had to add the port to my config to continue using `3000`:

`server: { port: 3000 },`

**Comment by daniel-nagy** [comment]
> Just a note for others: something changed with Vite, and I had to add the port to my config to continue using 3000

If port `3000` is in use (e.g. you already have Vite running in the background somewhere) then Vite will automatically use a different port.

**Comment by dfalling** [comment]
\> If port `3000` is in use (e.g. you already have Vite running in the background somewhere) then Vite will automatically use a different port.

For some reason Vite refuses to use port 3000 for me even though the port's open (double-checked with netstat). Specifying it in the config works though, no failure on launch because the port's already in use.
