### ISSUE TITLE
about modes

### ISSUE THREAD

**Issue by xudaotutou** [jihchi/vite-plugin-rescript#13]
* Can I use vite-plubin-rescript with custom mode ?
* I find this code  `      const needReScript =
        (command === 'serve' && mode === 'development') || command === 'build';
` 
* I think that `mode` should be replaced by `env.NODE_ENV`

**Comment by jihchi** [comment]
Good catch! 

The plugin won't launch ReScript compiler when we use `vite preview --mode <except "development">` to specify different mode.

I'll looking into it.

**Comment by jihchi** [comment]
The issue should be fixed in [`@jihchi/vite-plugin-rescript@4.1.1`](https://github.com/jihchi/vite-plugin-rescript/releases/tag/v4.1.1).
