### ISSUE TITLE
Unit tests time out when running coverage

### ISSUE THREAD

**Issue by jderochervlk** [jihchi/vite-plugin-rescript#20]
When running vitest with coverage unit tests time out.
> Note: the project where I encountered this bug had the tests written in typescript.

```
close timed out after 10000ms
Tests closed successfully but something prevents Vite server from exiting
You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
```

test config:
```
 test: {
    globals: true,
    environment: "jsdom",
    coverage: {
      reporter: ["json", "json-summary", "text"],
      provider: "v8",
      lines: 100,
      statements: 100,
      functions: 100,
    },
  },
```

Minimal reproduction: https://github.com/jderochervlk/rescript-vitest-plugin-bug
- Unit tests are written in TypeScript to test files compiled by ReScript
- To see error run `npm run test`
- To remove the error comment out `createReScriptPlugin()` in `vite.config.js`

**Comment by jihchi** [comment]
Hi @jderochervlk, thank you for the elaborated issue report, it is very helpful.

I have published a new version: `@jihchi/vite-plugin-rescript@5.3.1`. Please let me know if it does not work for you.

**Comment by joshderochervlk-simplisafe** [comment]
Sorry for the late response. This did solve my issue, thanks!
