### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by greyblake** [jihchi/vite-plugin-rescript#3]
Hi!
I'm rewriting my hobby project from TS to ReScript and I'd like to say thank you for ReScript Real World App and vite-plugin-rescript! 
It really helped to figure out some stuff.

**Comment by jihchi** [comment]
Hi @greyblake ,

You're welcome! I'd like to thank you too for your [#FromTypescriptToRescript](https://twitter.com/hashtag/FromTypescriptToRescript?src=hashtag_click) tweet series!
